Fix: output colors and getopts call wouldn't loop because it couldn't access arguments.

diff --git a/installcfg b/installcfg
--- a/installcfg
+++ b/installcfg
@@ -13,7 +13,6 @@ Blue='\e[0;34m'         # Blue
 Cyan='\e[0;36m'         # Cyan
 NC="\e[m"               # Color Reset
 
-IFS='\n'
 PKG_HELPER=""
 CSFML_SCRIPT_ADDRESS="https://raw.githubusercontent.com/Epitech/dump/master/build_csfml.sh"
 
@@ -22,17 +21,17 @@ CSFML_SCRIPT_ADDRESS="https://raw.githubusercontent.com/Epitech/dump/master/buil
 #####################################
 
 display_help () {
-    echo "Welcome to ${Yellow}Bogdzn's ezdump script${NC}, a basic tool to quickly dump whatever you need !"
-    echo "Here are the options you might need:"
-    echo "\t${Cyan}-h\t${NC}Display this message."
-    echo "\t${Cyan}-d\t${NC}Sets the dotfiles repository url (For your bashrc, etc...)."
-    echo "\t${Cyan}-f\t${NC}Sets the package list file path."
+    printf "Welcome to ${Yellow}Bogdzn's ezdump script${NC}, a basic tool to quickly dump whatever you need !\n"
+    printf "Here are the options you might need:\n"
+    printf "\t${Cyan}-h\t${NC}Display this message.\n"
+    printf "\t${Cyan}-d\t${NC}Sets the dotfiles repository url (For your bashrc, etc...).\n"
+    printf "\t${Cyan}-f\t${NC}Sets the package list file path.\n"
 }
 
 check_if_error () {
     if [ "$1" -ne 0 ]; then
         printf "${Red}ERROR.${NC}\n\n"
-        read -p "Do you want to exit the script ? [y/N]" yn
+        read -p "Do you want to exit the script ? [y/N] " yn
         case "$yn" in
             y|Y) exit 0 ;;
             *) return ;;
@@ -44,7 +43,7 @@ check_if_error () {
 }
 
 install_criterion () {
-    read -p "Do you want to install ${Blue}Epitech${NC}'s supported Criterion version ? [Y/n]" yn
+    read -p "Do you want to install Epitech's supported Criterion version ? [Y/n]" yn
     case "$yn" in
         n|N) return ;;
         *) ;;
@@ -57,15 +56,15 @@ install_criterion () {
 
     cd /tmp && rm "$TARBALL"; rm -rf "$DIR"
     install "wget"
-    printf "${Yellow}Installing ${Blue}Criterion${Yellow}:${NC}"
-    wget wget "${URL}/${TARBALL}" && tar xjf "$TARBALL"
+    printf "Installing Criterion: "
+    wget "${URL}/${TARBALL}" && tar xjf "$TARBALL"
     sudo sh -c "echo "/usr/local/lib" > /etc/ld.so.conf.d/criterion.conf && cp -r "$DIR"/include/* $"DST"/include && cp -r "$DIR"/lib/* "$DST"/lib/"
 
     check_if_error "$?"
 }
 
 install_csfml () {
-    read -p "Do you want to install ${Blue}Epitech${NC}'s supported CSFML version ? [Y/n]" yn
+    read -p "Do you want to install Epitech's supported CSFML version ? [Y/n]" yn
     case "$yn" in
         n|N) return ;;
         *) curl "$CSFML_SCRIPT_ADDRESS" | sudo bash ;;
@@ -78,10 +77,10 @@ update () {
     printf "${Yellow}Updating packages: ${NC}"
 
     case "$OS_TYPE" in
-        archlinux) sudo pacman --noconfirm -Syu ;;
-        debian) sudo apt -y update && sudo apt -y upgrade ;;
-        fedora) sudo dnf -y update ;;
-        opensuse) sudo zypper -y update ;;
+        archlinux) sudo pacman --noconfirm -Syu > /dev/null 1>&2 ;;
+        debian) sudo apt -y update && sudo apt -y upgrade > /dev/null 1>&2 ;;
+        fedora) sudo dnf -y update > /dev/null 1>&2 ;;
+        opensuse) sudo zypper -y update > /dev/null 1>&2 ;;
     esac
 
     check_if_error "$?"
@@ -120,12 +119,12 @@ get_package_helper () {
         *) ;;
     esac
 
-    read -p "Ok, please specify the name of the package installe you want to install: " pkg
+    read -p "Ok, please specify the name of the package installer you want to install: " pkg
     case "$pkg" in
         snap) PKG_HELPER="sudo snap install" && install "snapd" ;;
         flatpak) PKG_HELPER="sudo flatpak install" && install "flatpak" ;;
         yay) PKG_HELPER="yay -Syu --noconfirm" && install_yay ;;
-        *) echo "${Red}Error:${NC} unrecognised package manager. Please edit the script or file an issue." && exit 1 ;;
+        *) printf "${Red}Error:${NC} unrecognised package manager. Please edit the script or file an issue.\n" && exit 1 ;;
     esac
 }
 
@@ -145,8 +144,8 @@ get_os () {
 dotfiles () {
     printf "${Cyan}Installing dotfiles...${NC}\n"
     git clone "${DOTFILES_URL}" df || check_if_error "$?"
-    mv -v df/.config ~/
-    mv -v df/.*rc ~/
+    rm -rf ~/.config; rm -rf ~/.*rc
+    mv -v df/.config ~/; mv -v df/.*rc ~/
 }
 
 disable_systembeep () {
@@ -154,31 +153,30 @@ disable_systembeep () {
 }
 
 init_script () {
-
-     OS_TYPE=$(get_os)
-    PKG_MANAGER=$(get_pkg_manager)
-
-    if [[ "$EUID" -ne 0 ]] ; then
-        echo "${Red}This script must be run as root.${NC}"
-        exit 1
-
-    elif [[ "$OS_TYPE" = "" ]] ; then
-        echo "${Red}Error:${NC} Unsupported distribution."
-        echo "Only ${Cyan}Archlinux${NC}, ${Red}Debian${NC}, ${Blue}Fedora${NC} and ${Green}OpenSUSE${NC} are supported."
-        echo "Please modify the script or file an issue here: https://github.com/bogdzn/ezdump"
-        exit 1
-    fi
-
     # input handling is set here for convenience
-    while getopts "hd:f:" o; do case "${o}" in
+    while getopts "hd:f:" opt; do case "$opt" in
         h) display_help && exit 0 ;;
         d) DOTFILES_URL=${OPTARG} ;;
         f) PKG_FILE_PATH=${OPTARG} ;;
         *) printf "${Red}/!\\${NC} Invalid option: -${Yellow}%s${NC}\n" "$OPTARG" && exit 1 ;;
     esac done
 
-    [ -z "$DOTFILES_DIR" ] && DOTFILES_DIR="https://github.com/bogdzn/dotfiles"
+    OS_TYPE=$(get_os)
+    PKG_MANAGER=$(get_pkg_manager)
+
+    [ -z "$DOTFILES_URL" ] && DOTFILES_URL="https://github.com/bogdzn/dotfiles"
     [ -z "$PKG_FILE_PATH" ] && PKG_FILE_PATH="./pkgs"
+
+    if [[ "$EUID" -ne 0 ]] ; then
+        printf "${Red}This script must be run as root.${NC}\n"
+        exit 1
+
+    elif [[ "$OS_TYPE" = "" ]] ; then
+        printf "${Red}Error:${NC} Unsupported distribution.\n"
+        printf "Only ${Cyan}Archlinux${NC}, ${Red}Debian${NC}, ${Blue}Fedora${NC} and ${Green}OpenSUSE${NC} are supported.\n"
+        printf "Please modify the script or file an issue here: https://github.com/bogdzn/ezdump\n"
+        exit 1
+    fi
 }
 
 #####################################
@@ -186,7 +184,7 @@ init_script () {
 #####################################
 # todo add alwaysYes option and fakeInstall option for debug purposes
 
-init_script
+init_script "$@"
 
 update
 
